DevGohel/DevGohel/Controllers/Admin/TopicController.cs
using DevGohel.Models;
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DevGohel.Controllers.Admin
{
    public class TopicController : Controller
    {
        private BookDbContext _db;
        public HttpCookie userCookie;
        public int UserId;

        public TopicController()
        {
            _db = new BookDbContext();
        }

        private bool GetCookiesInformation()
        {
            if (Request.Cookies["devgoheladmin"] != null)
            {
                userCookie = HttpContext.Request.Cookies["devgoheladmin"];
                UserId = int.Parse(userCookie["AuthorId"].ToString());
                return true;
            }
            return false;
        }

        public ActionResult TIndex(int? page, string Search)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (Search != null)
            {
                var model = _db.Topics.Where(d => d.Name.Contains(Search) && d.TopicType == TopicType.Topic && d.AuthorId == UserId).OrderBy(o => o.Created).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
            else
            {
                var model = _db.Topics.OrderBy(d => d.Created).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
        }

        public PartialViewResult _SearchTopic(int? page, string Search = null)
        {
            if (GetCookiesInformation())
            {
                var model = _db.Topics.Where(d => d.Name.Contains(Search) && d.TopicType == TopicType.Topic && d.AuthorId == UserId).OrderByDescending(o => o.Name).ToList();
                return PartialView(model.ToPagedList(page ?? 1, 10));
            }
            else
                return PartialView();
        }

        public ActionResult Create()
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Ename,BgColor,TxColor,LabelId")] Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            topic.IsActive = true;
            topic.Created = DateTime.Now;
            topic.AuthorId = UserId;
            topic.TopicType = TopicType.Topic;
            if (ModelState.IsValid)
            {
                bool Exists = _db.Topics.Any(d => d.Name.Equals(topic.Name));
                if (!Exists)
                {
                    _db.Topics.Add(topic);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Try another label name");
                }
            }
            else
            {
                return Json("Model is not valid.");
            }
        }

        public ActionResult Edit(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Topic model = _db.Topics.Find(id);
            if (model == null)
            {
                return Redirect("~/Admin/Login");
            }
            if (model.AuthorId == UserId)
            {
                if (model == null)
                {
                    return HttpNotFound();
                }
                ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", model.LabelId);
                return View(model);
            }
            else
            {
                return Redirect("~/Author/Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TopicId,AuthorId,Name,Ename,TopicType,BgColor,TxColor,LabelId")] Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Author", null);

            topic.IsActive = true;
            topic.TopicType = TopicType.Topic;
            topic.Created = DateTime.Now;
            if (ModelState.IsValid)
            {
                if (userCookie == null)
                {
                    return RedirectToAction("Login", "User", null);
                }
                bool Exists = _db.Topics.Any(d => d.Name == topic.Name && d.TopicId != topic.TopicId);
                if (Exists)
                {
                    return Json("Try another label name");
                }
                else
                {
                    _db.Entry(topic).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json("");
                }
            }
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", topic.LabelId);
            return View(topic);
        }

        public ActionResult Delete(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = _db.Topics.Find(id);
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name");
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "TopicId")]Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            Topic topicGet = _db.Topics.Find(topic.TopicId);
            _db.Topics.Remove(topicGet);
            _db.SaveChanges();
            return Json("");
        }

        public ActionResult Detail(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Admin", null);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = _db.Topics.Find(id);
            topic.TDatas = _db.TDatas.Where(d => d.TopicId == topic.TopicId).ToList();
            if (topic != null && topic.AuthorId == UserId)
            {
                ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", topic.LabelId);
                return View(topic);
            }
            else
            {
                return Redirect("~/Admin/Login");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DevGohel/DevGohel/Controllers/SearchController.cs
using DevGohel.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace DevGohel.Controllers
{
    public class SearchController : Controller
    {
        string con = "";
        BookDbContext _db;

        public SearchController()
        {
            _db = new BookDbContext();
            con = ConfigurationManager.ConnectionStrings["BookDbContext"].ConnectionString;
        }
        public ActionResult Index(string search)
        {
            if (search == null)
                return RedirectToAction("Index", "Home", null);

            ViewBag.Advertise = null;
            if (Session["Advertise"] == null)
            {
                Sponser sponser = _db.Database.SqlQuery<Sponser>("exec spGetSponser").FirstOrDefault();
                Session.Add("Advertise", sponser.Body);
            }
            ViewBag.Advertise = Session["Advertise"];

            //SqlParameter @TType = new SqlParameter()
            //{
            //    ParameterName = "@TType",
            //    DbType = DbType.Int32,
            //    Value = (int)TopicType.Topic
            //};

            SqlParameter @Ename = new SqlParameter()
            {
                ParameterName = "@Ename",
                DbType = DbType.String,
                Value = search
            };
            object[] topicParameters = new object[] { @Ename };


            Topic topic = _db.Database.SqlQuery<Topic>("exec spGetTopicByENameSearch @Ename", topicParameters).FirstOrDefault();

            SqlParameter @TopicId = new SqlParameter()
            {
                ParameterName = "@TopicId",
                DbType = DbType.Int64,
                Value = topic.TopicId
            };

            object[] tdataParameters = new object[] { @TopicId };
            topic.TDatas = _db.Database.SqlQuery<TData>("exec spGetTopicIdData @TopicId", tdataParameters).ToList();


            SqlParameter @LabelId = new SqlParameter()
            {
                ParameterName = "@LabelId",
                DbType = DbType.Int64,
                Value = topic.LabelId
            };

            object[] labelParameters = new object[] { @LabelId };
            topic.Label = _db.Database.SqlQuery<Label>("exec spGetLabelById @LabelId", labelParameters).FirstOrDefault();

            SqlParameter @AuthorId = new SqlParameter()
            {
                ParameterName = "@AuthorId",
                DbType = DbType.Int64,
                Value = topic.AuthorId
            };

            object[] authorParameters = new object[] { @AuthorId };
            topic.Author = _db.Database.SqlQuery<Author>("exec spGetAuthorById @AuthorId", authorParameters).FirstOrDefault();


            if (topic != null)
            {
                return View(topic);
            }

            return View(returnTopicsIFNull(search));
        }

        public Topic returnTopicsIFNull(string search)
        {
            Topic Empty = new Topic();

            List<TData> LstTdata = new List<TData>();
            TData tData = new TData() { TdataId = 0, Name = "No records related to " + Convert.ToString(search), Body = "Sorry for inconvenience we haven't information related to " + Convert.ToString(search) };
            LstTdata.Add(tData);

            Empty.AuthorId = 0;
            Empty.Name = String.Empty;
            Empty.TopicId = 0;
            Empty.Name = "Not Found";
            Empty.Ename = search;
            Empty.TDatas = LstTdata;

            return Empty;
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DevGohel/DevGohel/Views/Topic/Create.cshtml
@model DevGohel.Models.Topic

@{
    ViewBag.Title = "Add Topic";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-start-admin">
    <div class="row">
        <div class="col-md-12">
            <h3>Add Topic</h3>
        </div>
        <div class="col-md-12">
            @using (Ajax.BeginForm("Create", new AjaxOptions { }))
            {
                @Html.AntiForgeryToken()
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>
                <div class="form-group input-group input-group-lg" title="Enter Topic Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NEW TOPIC NAME" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Search Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.Ename, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "AUTO NAME PROPERTY" } })
                    @Html.ValidationMessageFor(model => model.Ename, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Dispaly Background Color Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EnumDropDownListFor(model => model.BgColor, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BgColor, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Display Text Color Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EnumDropDownListFor(model => model.TxColor, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TxColor, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Select Label">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.DropDownList("LabelId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LabelId, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="submit" value="Save" onclick="submitUniversal(this, '@Url.Action("TIndex","Topic")');" class="btn btn-info" />
                    <a href="@Url.Action("TIndex","Topic")" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
        <div class="col-md-12">
            <div class="col-md-12 content-data">
                <div class="content-data-x nopadding">
                    <h3 id="bodyName">Profile Name</h3>
                    <p id="bodytext">
                        Your profile information...
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var contentBox = $("div.content-data")
            contentBox
                .css("background-color", $('#BgColor option:selected').text());
            contentBox
                .find("h3, p")
                .css("color", $('#TxColor option:selected').text());

            $("input#Name").on("keyup", function () {
                var inputstr = $(this).val();
                var bodyName = $("#bodyName");

                bodyName.text(inputstr);
                var val = inputstr.replace(/[^a-z0-9\s]/gi, '-').replace(/[_\s]/g, '-')
                $("input#Ename").val(val);
                bodyName.removeAttr("href");
            });

            $("#BgColor").change(function () {
                var bgColor = $("#BgColor option:selected").text();
                $("div.content-data").css("background-color", bgColor);
            });
            $("#TxColor").change(function () {
                var txColor = $("#TxColor option:selected").text();
                $("div.content-data").find("h3, p").css("color", txColor);
            });
        });

    </script>
}

DevGohel/DevGohel/Views/Topic/CreateTData.cshtml
@model DevGohel.Models.TData

@{
    ViewBag.Title = "Add Profile Information";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-start-admin">
    <div class="row">
        <div class="col-md-12">
            <h4>Profile Information</h4>
        </div>
        <div class="col-md-12">
            @using (Ajax.BeginForm("CreateProfile", new AjaxOptions { }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.TopicId)
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>
                <div class="form-group input-group input-group-lg" title="Enter Topic Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NEW INFORMATION TITLE" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Search Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "AUTO ORDER PROPERTY" } })
                    @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Display Text Color Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Enter Topic Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.ExtraText, new { htmlAttributes = new { @class = "form-control", @placeholder = "Paste Link", @disabled = "disabled" } })
                </div>
                <textarea id="Body" name="Body" class="form-control jqte-test" rows="15" type="text" placeholder="Write something about topic information"></textarea>
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger form-control-feedback" })
                <div class="form-group text-right top-twenty">
                    <input id="submit" type="submit" value="Save" onclick="CreateProfileData(this);" class="btn btn-info" />
                    <a href="@Url.Action("TIndex","Topic",null)" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/editor.js"></script>
    <script>
        $(document).ready(function () {

            GetMaxNumber('@Url.Action("GetMaxOrderNo","Profile")');
            $("input#Title").on("change", function () {
                GetMaxNumber('@Url.Action("GetMaxOrderNo","Profile")');
            });

            $('#Type').on("change", function () {
                var selectedType = $(this).val();
                if(selectedType!=0)
                {
                    $('input#ExtraText').removeAttr('disabled');
                }
                else
                {
                    $('input#ExtraText').attr('disabled','disabled');
                }
            });
        });
    </script>
}

DevGohel/DevGohel/Views/Topic/Detail.cshtml
@using DevGohel.Models
@model DevGohel.Models.Topic

@{
    ViewBag.Title = "Topic Data Information";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-start-admin">
    <div class="row">
        <div class="col-md-12">

            @if (Model == null)
            {
                <a href="@Url.Action("Create", "TData", new { id= Model.TopicId })" class="btn btn-default col-md-12">+ Profile Information</a>
            }
            else
            {
                <div class="row">
                    @Html.HiddenFor(model => model.BgColor)
                    @Html.HiddenFor(model => model.TxColor)
                    <div class="col-md-12">
                        <div id="contentBox" class="col-md-12 content-boxi">
                            <div class="col-lg-8">
                                <a id="bodyName" class="boxi" target="_blank" href='@Url.Action("Index", "Search", new { search=Model.Ename.ToString()})'>@Model.Name</a>
                            </div>
                            <div class="col-lg-4 text-right" style="padding:1px;">
                                <a href="@Url.Action("TIndex", "Topic", new { id = Model.TopicId })" title="Back to Topic" class="btn btn-default btn-xs">
                                    <span class="glyphicon glyphicon-backward"></span>
                                </a>
                                <a class="btn btn-default btn-xs" title="Add Topic Information" href="@Url.Action("Create", "TData", new { id = @Model.TopicId})">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
                <div id="topicinfo" class="co-md-12">
                    @if (Model.TDatas != null)
                    {
                        foreach (var data in Model.TDatas)
                        {
                            if (data.Type == TDataType.HtmlText)
                            {
                                <div class="col-lg-12 content-data" title="@data.Name">
                                    <div class="row">
                                        <div class="col-lg-12 content-data-x">
                                            <div class="head">@data.Name</div>
                                            <div>
                                                @Html.Raw(@data.Body)
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row text-right bg-danger" style="padding:5px;">
                                        <a href="@Url.Action("Edit", "TData", new { id = data.TdataId})" title="Edit" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-file"></span>
                                        </a>

                                        <a href="@Url.Action("Delete", "TData", new { id = data.TdataId })" title="Delete" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </a>
                                    </div>
                                </div>
                            }
                            else if (data.Type == TDataType.Youtube)
                            {
                                <div class="col-lg-12 content-data-youtube">
                                    <div class="row">
                                        <div class="col-lg-4 content-data-youtube-text">
                                            <div class="head">
                                                @data.Name
                                            </div>
                                            <div>
                                                @Html.Raw(@data.Body)
                                            </div>
                                        </div>
                                        <div class="col-lg-8 nopadding">
                                            <div class="videoWrapper">
                                                <iframe width="640" height="360" src="http://www.youtube.com/embed/@data.ExtraText?rel=0&hd=1" frameborder="0" allowfullscreen></iframe>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row text-right bg-danger" style="padding:5px;">
                                        <a href="@Url.Action("Edit", "TData", new { id = data.TdataId })" title="Edit" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-file"></span>
                                        </a>

                                        <a href="@Url.Action("Delete", "TData", new { id = data.TdataId })" title="Delete" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </a>
                                    </div>
                                </div>
                            }
                            else if (data.Type == TDataType.Files)
                            {
                                <div class="col-lg-12 content-data" title="@data.Name">
                                    <div class="row">
                                        <div class="col-lg-12 content-data-x">
                                            <div class="head">
                                                @data.Name
                                            </div>
                                            <div>
                                                @Html.Raw(@data.Body)
                                            </div>
                                        </div>
                                        <div class="col-lg-12 content-data-x bg-warning" style="border-top:1px solid #D1D1D1;">
                                            <div class="files btn-link" style="text-align:center;">
                                                <a href="@data.ExtraText">
                                                    <i class="glyphicon glyphicon-download"></i> Download
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row text-right bg-danger" style="padding:5px;">
                                        <a href="@Url.Action("Edit", "TData", new { id = data.TdataId })" title="Edit" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-file"></span>
                                        </a>

                                        <a href="@Url.Action("Delete", "TData", new { id = data.TdataId })" title="Delete" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </a>
                                    </div>
                                </div>
                            }
                            else if (data.Type == TDataType.Website)
                            {
                                <div class="col-lg-12 content-data" title="@data.Name">
                                    <div class="row">
                                        <div class="col-lg-12 content-data-x">
                                            <div class="head">
                                                @data.Name
                                            </div>
                                            <div>
                                                @Html.Raw(@data.Body)
                                            </div>
                                        </div>
                                        <div class="col-lg-12 content-data-x bg-info" style="border-top:1px solid #D1D1D1;">
                                            <div class="files btn-link" style="text-align:center;">
                                                <a href="@data.ExtraText" target="_blank">
                                                        <i class="glyphicon glyphicon-download"></i> Want to visit?
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row text-right bg-danger" style="padding:5px;">
                                        <a href="@Url.Action("Edit", "TData", new { id = data.TdataId })" title="Edit" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-file"></span>
                                        </a>

                                        <a href="@Url.Action("Delete", "TData", new { id = data.TdataId })" title="Delete" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </a>
                                    </div>
                                </div>
                            }
                        }
                    }
                </div>

            }

        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {


            var contentBox = $("div#contentBox")
            contentBox
                .css("background-color", $('#BgColor').val());
            contentBox
                .find("a.boxi")
                .css("color", $('#TxColor').val());


            $("#BgColor").change(function () {
                var bgColor = $("#BgColor option:selected").text();
                $("div#content-box").css("background-color", bgColor);
            });
            $("#TxColor").change(function () {
                var txColor = $("#TxColor option:selected").text();
                $("div#content-box")
                    .find("a.boxi")
                    .css("color", txColor);
            });
        });
    </script>
}

DevGohel/DevGohel/Views/Topic/_SearchTopic.cshtml
@using PagedList
@model IPagedList<DevGohel.Models.Topic>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ename)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.TopicId }) |
            @Html.ActionLink("Detail", "Detail", new { id = item.TopicId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.TopicId })
        </td>
    </tr>
}