DevGohel/DevGohel/Controllers/Admin/ProfileController.cs
using DevGohel.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
namespace DevGohel.Controllers.Admin
{
    public class ProfileController : Controller
    {
        private BookDbContext _db;
        public HttpCookie userCookie;
        public int UserId;

        public ProfileController()
        {
            _db = new BookDbContext();
        }

        private bool GetCookiesInformation()
        {
            if (Request.Cookies["devgoheladmin"] != null)
            {
                userCookie = HttpContext.Request.Cookies["devgoheladmin"];
                UserId = int.Parse(userCookie["AuthorId"].ToString());
                return true;
            }
            return false;
        }

        public ActionResult PIndex()
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            Topic topic = _db.Topics.Include(d => d.TDatas).FirstOrDefault(d => d.TopicType == TopicType.Author && d.AuthorId == UserId);

            return View(topic);

        }

        public ActionResult Create()
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Ename,BgColor,TxColor,LabelId")] Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            topic.IsActive = true;
            topic.Created = DateTime.Now;
            topic.AuthorId = UserId;
            topic.TopicType = TopicType.Author;
            if (ModelState.IsValid)
            {
                bool Exists = _db.Topics.Any(d => d.Name.Equals(topic.Name));
                if (!Exists)
                {
                    _db.Topics.Add(topic);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Try another label name");
                }
            }
            else
            {
                return Json("Model is not valid.");
            }
        }

        public ActionResult Edit(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Topic model = _db.Topics.Find(id);
            if (model == null)
            {
                return Redirect("~/Admin/Login");
            }
            if (model.AuthorId == UserId)
            {
                if (model == null)
                {
                    return HttpNotFound();
                }
                ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", model.LabelId);
                return View(model);
            }
            else
            {
                return Redirect("~/Author/Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TopicId,AuthorId,Name,Ename,TopicType,BgColor,TxColor,LabelId,Created")] Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Author", null);

            topic.IsActive = true;
            topic.TopicType = TopicType.Author;

            if (ModelState.IsValid)
            {
                if (userCookie == null)
                {
                    return RedirectToAction("Login", "User", null);
                }
                _db.Entry(topic).State = EntityState.Modified;
                _db.SaveChanges();
                return Json("");
            }
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", topic.LabelId);
            return View(topic);
        }

        public ActionResult CreateProfile(int TopicId)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Admin", null);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProfile([Bind(Include = "TdataId,Name,Body,OrderId,ExtraText,Type,TopicId")] TData tData)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            tData.IsActive = true;
            tData.Created = DateTime.Now;

            if (tData.Type == TDataType.HtmlText)
                tData.ExtraText = "";

            if (ModelState.IsValid)
            {
                _db.TDatas.Add(tData);
                _db.SaveChanges();
                return Json("");
            }

            return Json("Model is not valid.");
        }

        [HttpGet]
        public ActionResult GetMaxOrderNo(int? topicId)
        {
            if (topicId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<TData> tData = _db.TDatas.Where(t => t.TopicId == topicId).ToList();
            int maxOrderId = 0;
            if (tData.Count > 0)
            {
                maxOrderId = tData.Max(e => e.OrderId);
            }
            maxOrderId += 1;

            return Json(maxOrderId, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EditProfile(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TData model = _db.TDatas.Find(id);
            if (model == null)
            {
                return HttpNotFound("No records found.");
            }

            ViewBag.TopicId = new SelectList(_db.Topics, "TopicId", "Name", model.TopicId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile([Bind(Include = "TdataId,Name,Body,OrderId,ExtraText,Type,TopicId")] TData tData)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Admin", null);

            tData.IsActive = true;
            tData.Created = DateTime.Now;
            if (ModelState.IsValid)
            {
                _db.Entry(tData).State = EntityState.Modified;
                _db.SaveChanges();
                return Json("");
            }

            return Json("Model is not valid.");
        }

        public ActionResult DeleteP(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TData tData = _db.TDatas.Find(id);
            if (tData == null)
            {
                return HttpNotFound();
            }
            return View(tData);
        }

        [HttpPost, ActionName("DeleteP")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePConfirmed([Bind(Include = "TdataId")]TData tData)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            TData tDataGet = _db.TDatas.Find(tData.TdataId);
            _db.TDatas.Remove(tDataGet);
            _db.SaveChanges();
            return Json("");
        }
    }
}

DevGohel/DevGohel/Controllers/Admin/TopicController.cs
using DevGohel.Models;
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DevGohel.Controllers.Admin
{
    public class TopicController : Controller
    {
        private BookDbContext _db;
        public HttpCookie userCookie;
        public int UserId;

        public TopicController()
        {
            _db = new BookDbContext();
        }

        private bool GetCookiesInformation()
        {
            if (Request.Cookies["devgoheladmin"] != null)
            {
                userCookie = HttpContext.Request.Cookies["devgoheladmin"];
                UserId = int.Parse(userCookie["AuthorId"].ToString());
                return true;
            }
            return false;
        }

        public ActionResult TIndex(int? page, string Search)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (Search != null)
            {
                var model = _db.Topics.Where(d => d.Name.Contains(Search) && d.TopicType == TopicType.Topic && d.AuthorId == UserId).OrderBy(o => o.Created).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
            else
            {
                var model = _db.Topics.OrderBy(d => d.Created).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
        }

        public PartialViewResult _SearchTopic(int? page, string Search = null)
        {
            if (GetCookiesInformation())
            {
                var model = _db.Topics.Where(d => d.Name.Contains(Search) && d.TopicType == TopicType.Topic && d.AuthorId == UserId).OrderByDescending(o => o.Name).ToList();
                return PartialView(model.ToPagedList(page ?? 1, 10));
            }
            else
                return PartialView();
        }

        public ActionResult Create()
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Ename,BgColor,TxColor,LabelId")] Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            topic.IsActive = true;
            topic.Created = DateTime.Now;
            topic.AuthorId = UserId;
            topic.TopicType = TopicType.Topic;
            if (ModelState.IsValid)
            {
                bool Exists = _db.Topics.Any(d => d.Name.Equals(topic.Name));
                if (!Exists)
                {
                    _db.Topics.Add(topic);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Try another label name");
                }
            }
            else
            {
                return Json("Model is not valid.");
            }
        }

        public ActionResult Edit(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Topic model = _db.Topics.Find(id);
            if (model == null)
            {
                return Redirect("~/Admin/Login");
            }
            if (model.AuthorId == UserId)
            {
                if (model == null)
                {
                    return HttpNotFound();
                }
                ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", model.LabelId);
                return View(model);
            }
            else
            {
                return Redirect("~/Author/Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TopicId,AuthorId,Name,Ename,TopicType,BgColor,TxColor,LabelId")] Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Author", null);

            topic.IsActive = true;
            topic.TopicType = TopicType.Topic;
            topic.Created = DateTime.Now;
            if (ModelState.IsValid)
            {
                if (userCookie == null)
                {
                    return RedirectToAction("Login", "User", null);
                }
                bool Exists = _db.Topics.Any(d => d.Name == topic.Name && d.TopicId != topic.TopicId);
                if (Exists)
                {
                    return Json("Try another label name");
                }
                else
                {
                    _db.Entry(topic).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json("");
                }
            }
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", topic.LabelId);
            return View(topic);
        }

        public ActionResult Delete(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = _db.Topics.Find(id);
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name");
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "TopicId")]Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            Topic topicGet = _db.Topics.Find(topic.TopicId);
            _db.Topics.Remove(topicGet);
            _db.SaveChanges();
            return Json("");
        }

        public ActionResult Detail(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Admin", null);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = _db.Topics.Find(id);
            topic.TDatas = _db.TDatas.Where(d => d.TopicId == topic.TopicId).ToList();
            if (topic != null && topic.AuthorId == UserId)
            {
                ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", topic.LabelId);
                return View(topic);
            }
            else
            {
                return Redirect("~/Admin/Login");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DevGohel/DevGohel/Views/TData/Create.cshtml
@model DevGohel.Models.TData

@{
    ViewBag.Title = "Add Topic Information";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-start-admin">
    <div class="row">
        <div class="col-md-12">
            <h4>Topic Information</h4>
        </div>
        <div class="col-md-12">
            @using (Ajax.BeginForm("Create", new AjaxOptions { }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.TopicId)
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>
                <div class="form-group input-group input-group-lg" title="Enter Topic Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NEW INFORMATION TITLE" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Search Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "AUTO ORDER PROPERTY" } })
                    @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Display Text Color Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Enter Topic Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.ExtraText, new { htmlAttributes = new { @class = "form-control", @placeholder = "Paste Link", @disabled = "disabled" } })
                </div>
                <textarea id="Body" name="Body" class="form-control jqte-test" rows="15" type="text" placeholder="Write something about topic information"></textarea>
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger form-control-feedback" })
                <div class="form-group text-right top-twenty">
                    <input id="submit" type="submit" value="Save" onclick="CreateTdatas(this,'@Url.Action("Detail", "Topic", new { id = Model.TopicId })');" class="btn btn-info" />
                    <a href="@Url.Action("Detail", "Topic", new { id = Model.TopicId})" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/editor.js"></script>
    <script>
        $(document).ready(function () {

            GetMaxNumber('@Url.Action("GetMaxOrderNo","Profile")');
            $("input#Title").on("change", function () {
                GetMaxNumber('@Url.Action("GetMaxOrderNo","Profile")');
            });

            $('#Type').on("change", function () {
                var selectedType = $(this).val();
                if(selectedType!=0)
                {
                    $('input#ExtraText').removeAttr('disabled');
                }
                else
                {
                    $('input#ExtraText').attr('disabled','disabled');
                }
            });
        });
    </script>
}

DevGohel/DevGohel/Views/TData/Delete.cshtml
@model DevGohel.Models.TData

@{
    ViewBag.Title = "Delete Information";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-start-admin">
    <div class="row">
        <div class="col-md-12">
            <h4>Are you sure want to remove this?</h4>
        </div>
        <div class="col-md-12">
            @using (Ajax.BeginForm("Delete", new AjaxOptions { }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.TopicId)
                @Html.HiddenFor(model => model.TdataId)
                @Html.HiddenFor(model => model.Created)
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>
                <div class="form-group input-group input-group-lg" title="Enter Topic Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NEW INFORMATION TITLE" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <textarea id="Body" name="Body" class="form-control jqte-test" rows="15" type="text" placeholder="Write something about topic information">
                    @Model.Body
                </textarea>
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger form-control-feedback" })
                <div class="form-group text-right top-twenty">
                    <input id="submit" type="button" value="Delete" onclick="submitUniversal(this,'@Url.Action("Detail", "Topic", new { id = Model.TopicId })');" class="btn btn-danger" />
                    <a href="@Url.Action("Detail", "Topic", new { id = Model.TopicId})" class=" btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/editor.js"></script>
}

DevGohel/DevGohel/Views/TData/Edit.cshtml
@model DevGohel.Models.TData

@{
    ViewBag.Title = "Edit Topic Information";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-start-admin">
    <div class="row">
        <div class="col-md-12">
            <h4>Topic Information</h4>
        </div>
        <div class="col-md-12">
            @using (Ajax.BeginForm("Edit", new AjaxOptions { }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.TopicId)
                @Html.HiddenFor(model => model.TdataId)
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>
                <div class="form-group input-group input-group-lg" title="Enter Topic Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NEW INFORMATION TITLE" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Search Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "AUTO ORDER PROPERTY" } })
                    @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Display Text Color Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg" title="Enter Topic Name">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-copy"></i></span>
                    @Html.EditorFor(model => model.ExtraText, new { htmlAttributes = new { @class = "form-control", @placeholder = "Paste Link", @disabled = "disabled" } })
                </div>
                <textarea id="Body" name="Body" class="form-control jqte-test" rows="15" type="text" placeholder="Write something about topic information">
                    @Model.Body
                </textarea>
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger form-control-feedback" })
                <div class="form-group text-right top-twenty">
                    <input id="submit" type="submit" value="Edit" onclick="CreateTdatas(this,'@Url.Action("Detail", "Topic", new { id = Model.TopicId })');" class="btn btn-success" />
                    <a href="@Url.Action("Detail", "Topic", new { id = Model.TopicId})" class=" btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/editor.js"></script>
    <script>
        $(document).ready(function () {

            $('#Type').on("change", function () {
                var selectedType = $(this).val();
                if(selectedType!=0)
                {
                    $('input#ExtraText').removeAttr('disabled');
                }
                else
                {
                    $('input#ExtraText').attr('disabled','disabled');
                }
            });
        });
    </script>
}