DevGohel/DevGohel/Controllers/Admin/LabelController.cs
using DevGohel.Models;
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DevGohel.Controllers.Admin
{
    public class LabelController : Controller
    {
        BookDbContext _db;
        public HttpCookie userCookie;
        public int UserId;

        public LabelController()
        {
            _db = new BookDbContext();
        }

        private bool GetCookiesInformation()
        {
            if (Request.Cookies["devgoheladmin"] != null)
            {
                userCookie = HttpContext.Request.Cookies["devgoheladmin"];
                UserId = int.Parse(userCookie["AuthorId"].ToString());
                return true;
            }
            return false;
        }

        public ActionResult LIndex(int? page, string Search = null)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (Search != null)
            {
                var model = _db.Labels.Where(d => d.Name.Contains(Search)).OrderByDescending(o => o.Name).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
            else
            {
                var model = _db.Labels.OrderByDescending(d => d.Name).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }

        }
        public PartialViewResult _SearchLabel(int? page, string Search = null)
        {
            if (GetCookiesInformation())
            {
                var model = _db.Labels.Where(d => d.Name.Contains(Search)).OrderByDescending(o => o.Name).ToList();
                return PartialView(model.ToPagedList(page ?? 1, 10));
            }
            else
                return PartialView();
        }

        public ActionResult Create()
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,EName")] Label label)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            label.Created = DateTime.Now;
            label.IsActive = true;
            if (ModelState.IsValid)
            {
                bool Exists = _db.Labels.Any(d => d.Name.Equals(label.Name));
                if (!Exists)
                {
                    _db.Labels.Add(label);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Try another label name");
                }
            }
            else
            {
                return Json("Model is not valid.");
            }
        }

        public ActionResult Edit(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Label label = _db.Labels.Find(id);
            if (label == null)
            {
                return HttpNotFound();
            }
            return View(label);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LabelId,Name,EName,IsActive")] Label label)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            label.Created = DateTime.Now;
            if (ModelState.IsValid)
            {
                bool Exists = _db.Labels.Any(d => d.Name == label.Name && d.LabelId != label.LabelId);
                if (Exists)
                {
                    return Json("Try another label name");
                }
                else
                {
                    _db.Entry(label).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json("");
                }
            }
            else
            {
                return Json("Model is not valid.");
            }
        }

        public ActionResult Delete(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Label label = _db.Labels.Find(id);
            if (label == null)
            {
                return HttpNotFound();
            }
            return View(label);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "LabelId")] Label label)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            Label labelGet = _db.Labels.Find(label.LabelId);
            _db.Labels.Remove(labelGet);
            _db.SaveChanges();
            return Json("");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

        public System.Collections.Generic.List<Label> List { get; set; }
    }
}

DevGohel/DevGohel/Controllers/Admin/TopicController.cs
using DevGohel.Models;
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DevGohel.Controllers.Admin
{
    public class TopicController : Controller
    {
        private BookDbContext _db;
        public HttpCookie userCookie;
        public int UserId;

        public TopicController()
        {
            _db = new BookDbContext();
        }

        private bool GetCookiesInformation()
        {
            if (Request.Cookies["devgoheladmin"] != null)
            {
                userCookie = HttpContext.Request.Cookies["devgoheladmin"];
                UserId = int.Parse(userCookie["AuthorId"].ToString());
                return true;
            }
            return false;
        }

        public ActionResult TIndex(int? page, string Search)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (Search != null)
            {
                var model = _db.Topics.Where(d => d.Name.Contains(Search) && d.TopicType == TopicType.Topic && d.AuthorId == UserId).OrderBy(o => o.Created).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
            else
            {
                var model = _db.Topics.OrderBy(d => d.Created).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
        }

        public PartialViewResult _SearchTopic(int? page, string Search = null)
        {
            if (GetCookiesInformation())
            {
                var model = _db.Topics.Where(d => d.Name.Contains(Search) && d.TopicType == TopicType.Topic && d.AuthorId == UserId).OrderByDescending(o => o.Name).ToList();
                return PartialView(model.ToPagedList(page ?? 1, 10));
            }
            else
                return PartialView();
        }

        public ActionResult Create()
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Ename,BgColor,TxColor,LabelId")] Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            topic.IsActive = true;
            topic.Created = DateTime.Now;
            topic.AuthorId = UserId;
            topic.TopicType = TopicType.Topic;
            if (ModelState.IsValid)
            {
                bool Exists = _db.Topics.Any(d => d.Name.Equals(topic.Name));
                if (!Exists)
                {
                    _db.Topics.Add(topic);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Try another label name");
                }
            }
            else
            {
                return Json("Model is not valid.");
            }
        }

        public ActionResult Edit(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Topic model = _db.Topics.Find(id);
            if (model == null)
            {
                return Redirect("~/Admin/Login");
            }
            if (model.AuthorId == UserId)
            {
                if (model == null)
                {
                    return HttpNotFound();
                }
                ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", model.LabelId);
                return View(model);
            }
            else
            {
                return Redirect("~/Author/Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TopicId,AuthorId,Name,Ename,TopicType,BgColor,TxColor,LabelId")] Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Author", null);

            topic.IsActive = true;
            topic.TopicType = TopicType.Topic;
            topic.Created = DateTime.Now;
            if (ModelState.IsValid)
            {
                if (userCookie == null)
                {
                    return RedirectToAction("Login", "User", null);
                }
                bool Exists = _db.Topics.Any(d => d.Name == topic.Name && d.TopicId != topic.TopicId);
                if (Exists)
                {
                    return Json("Try another label name");
                }
                else
                {
                    _db.Entry(topic).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json("");
                }
            }
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", topic.LabelId);
            return View(topic);
        }

        public ActionResult Delete(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = _db.Topics.Find(id);
            ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name");
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "TopicId")]Topic topic)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("AIndex", "Author", null);

            Topic topicGet = _db.Topics.Find(topic.TopicId);
            _db.Topics.Remove(topicGet);
            _db.SaveChanges();
            return Json("");
        }

        public ActionResult Detail(long? id)
        {
            if (!GetCookiesInformation())
                return RedirectToAction("Login", "Admin", null);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = _db.Topics.Find(id);
            topic.TDatas = _db.TDatas.Where(d => d.TopicId == topic.TopicId).ToList();
            if (topic != null && topic.AuthorId == UserId)
            {
                ViewBag.LabelId = new SelectList(_db.Labels, "LabelId", "Name", topic.LabelId);
                return View(topic);
            }
            else
            {
                return Redirect("~/Admin/Login");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DevGohel/DevGohel/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin - @ViewBag.Title</title>
    <link rel="shortcut icon" href="~/lOGO.ico">
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-header">
                    <a href="@Url.Action("AIndex","Author",null)" class="navbar-brand">
                        @Request.Cookies["devgoheladmin"]["Name"].ToString()
                    </a>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("LIndex","Label",null)">LABELS</a></li>
                    <li><a href="@Url.Action("SIndex","Sponser",null)">SPONSER</a></li>
                    <li><a href="@Url.Action("TIndex","Topic",null)">TOPICS</a></li>
                    <li><a href="@Url.Action("FIndex","File",null)">FILES</a></li>
                    <li><a href="@Url.Action("PIndex","Profile",null)">PROFILE</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right" title="LOGOUT">
                    <li><a href="@Url.Action("Logout","Author",null)">LOGOUT</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="my-body">
        <div class="container" style="margin-bottom:30px;">
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DevGohel/DevGohel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/lOGO.ico">
    <title>Devendra Gohel - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div id="home" class="container-fluid">
        <div class="row top-menu">
            <div class="container" title="back to home page">
                <a class="a-link" href="/">DEVENDRA GOHEL</a>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <div class="container-fluid" style="margin-top:30px;">
        <div class="row">
            <div style="text-align:center;  margin-bottom:10px;">
                &copy; @DateTime.Now.Year Devendra Gohel. All contents are copyright.
            </div>
            <div style="text-align:center;  margin-bottom:20px;">
                <a href="@Url.Action("Sitemap","Home",null)">sitemap</a>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
    $(document).ready(function () {
        $('a[href*="#"]:not([href="#"])').click(function () {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html, body').animate({
                        scrollTop: target.offset().top
                    }, 500);
                    return false;
                }
            }
        });
    });
    </script>

    @RenderSection("scripts", required: false)

</body>
</html>

DevGohel/DevGohel/Views/Shared/_MyView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DevGohel", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>